[build]
    base = "/"
    publish = "dist/apps/website"
    command = "nx build website"

[context.production]
    base = "/"
    publish = "dist/apps/website"
    command = "nx build website --prod"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"